# Requirements

In [1]:
!pip install insightface

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.5/439.5 kB 5.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 90.2 MB/s eta 0:00:00
  Created wheel for insightface: filename=insightface-0.7.3-cp310-cp310-linux_x86_64.whl size=1055391 sha256=edbc7f379b199eae91ca31b76cc30260eac16cb80c3c6946ce91e6bc5b46a9fb
  Stored in directory: /root/.cache/pip/wheels/e3/d0/80/e3773fb8b6d1cca87ea1d33d9b1f20a223a6493c896da249b5
Successfully built insightface


In [2]:
!pip install opencv-python

In [3]:
!pip install tensorflow opencv-python-headless

In [4]:
import pandas as pd
import numpy as np

# Insightface

In [5]:
!pip install onnxruntime

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 50.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 8.1 MB/s eta 0:00:00


In [6]:
import cv2
from insightface.app import FaceAnalysis

app = FaceAnalysis()

/usr/local/lib/python3.10/dist-packages/albumentations/__init__.py:24: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.20). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()


download_path: /root/.insightface/models/buffalo_l


100%|██████████| 281857/281857 [00:11<00:00, 23859.39KB/s]
/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(


Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5


In [7]:
app.prepare(ctx_id=0, det_size=(640, 640))  # Use GPU if available

def find_embedding(img_path):
    img = cv2.imread(img_path)
    faces = app.get(img)
    embedding = faces[0].embedding  # First face's embedding
    return embedding


set det-size: (640, 640)


In [ ]:
# Demo
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Dipu_1.jpg"
embedding = find_embedding(img_path)

/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


# Creating Embeddings and Testing

### Kuldeep_embeddings

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Kuldeep_1.jpeg"
embedding_1 = find_embedding(img_path)
embedding_1

/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


array([ 3.06950063e-02, -1.09808850e+00, -1.24213243e+00, -3.71238366e-02,
       -1.18805194e+00,  3.54216993e-01,  1.35472548e+00,  7.32466459e-01,
       -4.56649870e-01, -5.68514705e-01,  6.44295692e-01,  1.62204099e+00,
       -5.26422858e-01, -1.52585340e+00, -8.54782224e-01, -1.59099209e+00,
       -7.41351664e-01,  1.24147141e+00,  7.73197293e-01, -2.63876975e-01,
        1.31182051e+00, -1.57074463e+00, -1.47874284e+00, -8.68906081e-01,
       -2.77026176e-01, -1.09625411e+00, -9.52483714e-02, -3.49819571e-01,
       -4.08856809e-01,  3.18154782e-01, -1.59786239e-01,  2.58970350e-01,
       -2.73798048e-01,  3.85130644e-01,  1.18186784e+00, -1.25274253e+00,
       -1.91016746e+00, -4.90691930e-01,  8.52062106e-01,  5.63306391e-01,
       -4.27622557e-01,  9.50189412e-01, -5.94472528e-01,  2.52761066e-01,
        6.91867352e-01, -1.78654313e+00, -6.38423622e-01,  9.65562582e-01,
        1.55964291e+00, -1.37691450e+00,  3.40328842e-01,  1.54767203e+00,
        1.31620026e+00, -

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Kuldeep 2.jpeg"
embedding_2 = find_embedding(img_path)
embedding_2

/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


array([-5.73803067e-01, -4.03260261e-01, -7.51175046e-01,  4.41314369e-01,
       -1.69785225e+00,  1.46941215e-01,  7.97987700e-01,  4.25149500e-01,
       -5.97987883e-03, -5.68062484e-01,  4.91450489e-01,  1.18999624e+00,
       -9.69170928e-01, -7.96214461e-01, -5.42042732e-01, -1.69150269e+00,
       -8.85550320e-01,  5.89846015e-01,  8.35938513e-01, -4.49747220e-02,
        1.46473527e+00, -9.59069610e-01, -1.88665032e+00, -5.33958495e-01,
       -6.62141383e-01, -1.40905976e+00, -1.16002488e+00, -1.16251898e+00,
        1.11645527e-01, -2.90043682e-01, -1.34475783e-01,  1.01589486e-01,
        4.89000045e-03, -5.57979941e-01,  2.09845170e-01, -2.14208198e+00,
       -2.59932423e+00,  1.38791502e-01,  9.46038842e-01,  8.92280519e-01,
       -1.04105830e+00,  1.05641723e+00, -3.42747152e-01, -2.22975403e-01,
        6.00832343e-01, -2.08745933e+00, -1.18289101e+00,  6.48958147e-01,
        1.59167898e+00, -1.18752904e-02,  5.83609045e-02,  1.03377306e+00,
        1.48426914e+00, -

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Kuldeep_3.jpeg"
embedding_3 = find_embedding(img_path)
embedding_3

array([ 0.22750014, -0.8450658 , -1.2146282 ,  0.8734242 , -2.1122515 ,
        0.5836936 ,  1.5906315 , -0.00924716, -0.5775658 , -0.8858779 ,
        1.0686024 ,  0.28475878, -0.24056152, -0.7416115 , -1.8694422 ,
       -1.509463  , -0.9145782 ,  1.2890964 ,  0.7514544 , -0.288885  ,
        1.5403343 , -1.0059415 , -1.3433049 ,  0.17399079, -0.84547746,
       -0.75984627,  0.07955519, -0.8017165 , -0.84136575, -0.8338231 ,
        0.7993201 ,  0.750464  , -0.40844226,  0.37745833, -0.11058129,
       -2.0412753 , -1.0942602 ,  0.53889173,  0.85793257,  0.59263635,
       -0.60100013,  2.1711526 , -1.9732985 ,  0.5241308 ,  0.81915617,
       -1.2528944 , -0.27649462,  0.49869144,  0.7579192 , -1.0504727 ,
        1.0842037 ,  0.19266184,  1.8149788 , -0.44399646, -0.33425432,
        0.413059  ,  0.01586372, -1.0102559 , -1.2979894 ,  0.9266593 ,
       -1.1027055 , -0.87711906, -0.36695105, -0.7020737 , -0.04106342,
        1.5447799 , -0.9694657 ,  0.06425989, -1.1127375 , -0.29

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Kuldeep_4.jpeg"
embedding_8 = find_embedding(img_path)
embedding_8

/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


array([-6.87192798e-01, -7.52535641e-01, -8.37128937e-01,  6.21786118e-02,
       -8.90190601e-01,  5.68205833e-01,  9.20860410e-01, -2.13435382e-01,
       -4.82342154e-01, -1.41758204e+00, -6.08813167e-01,  1.11330676e+00,
       -1.24558344e-01, -1.88718081e+00, -1.09841771e-01,  1.01784468e-01,
       -2.12515616e+00,  8.00014019e-01,  1.16578996e+00, -8.22581470e-01,
        4.53327119e-01,  2.95786560e-01, -1.23480582e+00, -1.06059933e+00,
       -5.26305676e-01, -8.17859828e-01, -6.83273613e-01, -1.87960970e+00,
       -6.44179732e-02,  8.67342353e-01,  3.18178713e-01,  4.90896046e-01,
        3.79982702e-02,  9.11400139e-01,  9.72088635e-01, -7.58026242e-01,
       -2.66630793e+00, -4.04117405e-01,  7.74057269e-01,  5.94827533e-01,
       -9.60874081e-01,  1.61137104e+00, -2.47825071e-01, -4.51103956e-01,
        1.07155240e+00, -1.45846486e+00, -1.20860910e+00,  7.25899398e-01,
        9.97780800e-01, -3.40768844e-01, -1.26563907e-01,  8.67435455e-01,
        1.04294503e+00, -

### Jayanta_embeddings

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Jayanta_1.jpeg"
embedding_4 = find_embedding(img_path)
embedding_4

/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


array([-8.74342769e-02,  4.71694708e-01,  5.50218642e-01,  1.61864668e-01,
        9.60988045e-01,  1.29003242e-01, -1.03240609e-02, -1.68563023e-01,
       -1.97162151e+00, -1.76073480e+00, -2.64429879e+00, -1.58435166e-01,
        6.10093474e-01,  8.27108249e-02,  1.22967219e+00,  1.26204765e+00,
        3.12838107e-01, -8.17644298e-02, -1.02166402e+00, -1.45270097e+00,
       -1.38146269e+00,  2.80454844e-01, -1.55165052e+00, -1.93801612e-01,
       -5.66610157e-01, -1.69988543e-01,  5.41822433e-01, -8.48609567e-01,
       -9.86670375e-01, -2.42245722e+00, -6.68979168e-01,  3.80548447e-01,
        1.33665526e+00, -3.09716761e-01,  3.03596020e-01,  2.01635218e+00,
       -1.43147564e+00,  3.81649911e-01,  6.31464958e-01, -1.81060523e-01,
       -6.61546290e-01, -1.29576766e+00,  2.51866430e-01, -1.28348315e+00,
       -7.86814451e-01, -1.71488309e+00,  1.30070233e+00, -1.24967766e+00,
        7.78061986e-01,  7.52915442e-01,  5.68264902e-01,  1.60357226e-02,
        6.60531998e-01,  

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Jayata_2.jpeg"
embedding_5 = find_embedding(img_path)
embedding_5

array([ 0.3910001 , -0.21090579,  0.686136  ,  0.81403863,  0.5790426 ,
        0.34831107, -0.5428613 ,  0.666421  , -2.5023685 , -1.8421278 ,
       -2.4909976 ,  0.24135096,  1.3998892 ,  0.35017964,  0.874781  ,
        1.2959905 , -0.09131309, -0.77881694, -0.74144095, -1.0536453 ,
       -1.7059295 , -0.299019  , -1.6583848 , -0.09530699, -1.3392853 ,
       -0.532012  ,  0.99446297, -0.7989397 , -1.0401226 , -2.7483454 ,
       -0.71201986,  0.8906696 ,  1.0786378 ,  0.4507519 ,  0.8598959 ,
        2.3010774 , -1.3308284 ,  1.1746099 ,  0.77239   ,  0.1165351 ,
       -0.58451414, -1.0844907 ,  1.19939   , -2.0966432 , -0.43034682,
       -1.6230757 ,  1.1588448 , -1.1980456 ,  0.6291815 ,  0.8831857 ,
        1.3161981 , -0.19598196,  0.45115665,  0.6626873 , -0.6586884 ,
       -0.3746682 , -1.1445658 ,  0.9994626 ,  0.29554766, -0.19656919,
        0.49206617, -1.2621577 , -0.07588612,  0.15499185, -0.48050657,
       -0.18395779,  0.22738416, -1.4807929 ,  0.82263887, -0.09

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Jayanta_3.jpeg"
embedding_6 = find_embedding(img_path)
embedding_6

array([-2.54690200e-01,  2.48446837e-01,  4.06265557e-01,  6.92739844e-01,
        6.87575817e-01, -1.52909532e-02,  1.68369524e-02,  6.25096679e-01,
       -1.70879138e+00, -1.98187757e+00, -2.15872979e+00,  3.98588538e-01,
        1.33257687e+00,  4.31355625e-01,  7.76780486e-01,  1.35094941e+00,
        3.30406457e-01, -6.26186579e-02, -1.29181623e+00, -6.39741421e-01,
       -1.67888832e+00, -8.45410883e-01, -1.36975002e+00, -4.35829848e-01,
       -1.35650337e+00, -3.58000576e-01,  1.49557495e+00, -1.21307278e+00,
       -1.21350420e+00, -2.88210821e+00, -4.75842431e-02,  8.12529474e-02,
        1.13769019e+00, -2.78962702e-01,  7.01234102e-01,  1.71086919e+00,
       -1.09557259e+00,  2.32102185e-01,  9.85595822e-01,  4.90637451e-01,
       -6.98331952e-01, -1.18866920e+00,  1.10627830e+00, -7.07522810e-01,
       -1.05944026e+00, -1.93068099e+00,  1.21830010e+00, -3.87539208e-01,
        9.90260839e-01,  4.46044981e-01,  1.34531021e+00,  1.63107023e-01,
       -6.60588592e-02,  

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Jayanta_4.jpeg"
embedding_7 = find_embedding(img_path)
embedding_7

/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


array([ 0.30195183, -0.10956549,  0.51277244,  0.905845  ,  1.0135758 ,
        0.8915728 , -0.32677615,  0.3732322 , -2.2751956 , -2.0628834 ,
       -1.7298124 ,  0.07164392,  1.5475208 ,  0.44540337,  0.83895147,
        1.0411212 ,  0.633136  , -0.6038312 , -0.77093   , -1.2313964 ,
       -1.7411193 , -0.36669153, -1.0126941 , -0.04968506, -1.8164062 ,
       -0.66786623,  0.64435804, -1.1019711 , -1.1120092 , -2.4823775 ,
       -0.5880204 ,  0.6874372 ,  1.3848257 ,  0.27728826,  1.4055061 ,
        2.0623684 , -1.0664012 ,  1.1893634 ,  0.78572524,  0.16881181,
       -0.9297424 , -1.3272732 ,  0.9294224 , -2.3911223 , -0.21497405,
       -1.6906154 ,  0.674512  , -0.67824024,  0.5647982 ,  1.1541647 ,
        1.1024969 , -0.90523803, -0.3183572 ,  0.9691543 , -1.0673882 ,
       -0.16647086, -1.2324271 ,  0.6541601 , -0.30156165, -0.47068524,
        0.3335737 , -1.8584677 , -0.81646585,  0.71881616, -0.6440044 ,
       -0.20729338,  0.01655761, -0.91764534,  1.1636524 , -0.10

### Dipu_embeddings

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Dipu_1.jpg"
Dipu_embedding_1 = find_embedding(img_path)
# Dipu_embedding_1

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Dipu_2.jpg"
Dipu_embedding_2 = find_embedding(img_path)
# Dipu_embedding_2

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Dipu_3.jpg"
Dipu_embedding_3 = find_embedding(img_path)
# Dipu_embedding_3

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Dipu_4.jpg"
Dipu_embedding_4 = find_embedding(img_path)
# Dipu_embedding_4

### Sambit_embedding

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Sambit_1.jpg"
Sambit_embedding_1 = find_embedding(img_path)
# Sambit_embedding_1

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Sambit_2.jpg"
Sambit_embedding_2 = find_embedding(img_path)
# Sambit_embedding_2

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Sambit_3.jpg"
Sambit_embedding_3 = find_embedding(img_path)
# Sambit_embedding_3

In [ ]:
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Sambit_4.jpeg"
Sambit_embedding_4 = find_embedding(img_path)
# Sambit_embedding_4

In [ ]:
# img_path = "abcd.jpg"
# Sambit_embedding_5 = find_embedding(img_path)
# # Sambit_embedding_5

In [ ]:
face_1 = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Sambit_5.jpg"
face_2 = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Sambit_6.jpg"

Sambit_embedding_5 = find_embedding(face_1)
Sambit_embedding_6 = find_embedding(face_2)

No face detected in the image.
No face detected in the image.


## Kuldeep_Testing



---

0.77 Minimum
Reason - Side standing (Positioning/Posture)


---




In [ ]:
cosine_similarity = np.dot(embedding_1, embedding_2) / (np.linalg.norm(embedding_1) * np.linalg.norm(embedding_2))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_1 - embedding_2)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.8320344686508179
Euclidean Distance: 13.39112377166748


In [ ]:
cosine_similarity = np.dot(embedding_1, embedding_3) / (np.linalg.norm(embedding_1) * np.linalg.norm(embedding_3))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_1 - embedding_3)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.7715832591056824
Euclidean Distance: 15.662611961364746


In [ ]:
cosine_similarity = np.dot(embedding_1, embedding_8) / (np.linalg.norm(embedding_1) * np.linalg.norm(embedding_8))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_1 - embedding_8)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.7930103540420532
Euclidean Distance: 14.728375434875488


## jayanta_Testing

In [ ]:
cosine_similarity = np.dot(embedding_4, embedding_5) / (np.linalg.norm(embedding_4) * np.linalg.norm(embedding_5))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_4 - embedding_5)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.9036219120025635
Euclidean Distance: 9.99468994140625


In [ ]:
cosine_similarity = np.dot(embedding_4, embedding_6) / (np.linalg.norm(embedding_4) * np.linalg.norm(embedding_6))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_4 - embedding_6)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.8582111597061157
Euclidean Distance: 11.810728073120117


In [ ]:
cosine_similarity = np.dot(embedding_4, embedding_7) / (np.linalg.norm(embedding_4) * np.linalg.norm(embedding_7))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_4 - embedding_7)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.820319652557373
Euclidean Distance: 13.56571102142334


## Dipu_Testing

In [ ]:
cosine_similarity = np.dot(Dipu_embedding_1, Dipu_embedding_2) / (np.linalg.norm(Dipu_embedding_1) * np.linalg.norm(Dipu_embedding_2))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Dipu_embedding_1 - Dipu_embedding_2)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.8147825598716736
Euclidean Distance: 14.462912559509277


In [ ]:
cosine_similarity = np.dot(Dipu_embedding_2, Dipu_embedding_2) / (np.linalg.norm(Dipu_embedding_2) * np.linalg.norm(Dipu_embedding_2))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Dipu_embedding_2 - Dipu_embedding_2)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 1.0
Euclidean Distance: 0.0


In [ ]:
cosine_similarity = np.dot(Dipu_embedding_2, Dipu_embedding_3) / (np.linalg.norm(Dipu_embedding_2) * np.linalg.norm(Dipu_embedding_3))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Dipu_embedding_2 - Dipu_embedding_3)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.9309988021850586
Euclidean Distance: 8.945442199707031


In [ ]:
cosine_similarity = np.dot(Dipu_embedding_1, Dipu_embedding_3) / (np.linalg.norm(Dipu_embedding_1) * np.linalg.norm(Dipu_embedding_3))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Dipu_embedding_1 - Dipu_embedding_3)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.830713152885437
Euclidean Distance: 13.947202682495117


In [ ]:
cosine_similarity = np.dot(Dipu_embedding_2, Dipu_embedding_4) / (np.linalg.norm(Dipu_embedding_2) * np.linalg.norm(Dipu_embedding_4))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Dipu_embedding_2 - Dipu_embedding_4)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.9404681921005249
Euclidean Distance: 8.176904678344727


## Sambit_Testing

In [ ]:
cosine_similarity = np.dot(Sambit_embedding_1, Sambit_embedding_2) / (np.linalg.norm(Sambit_embedding_1) * np.linalg.norm(Sambit_embedding_2))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Sambit_embedding_1 - Sambit_embedding_2)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.7684457898139954
Euclidean Distance: 15.961167335510254


In [ ]:
cosine_similarity = np.dot(Sambit_embedding_5, Sambit_embedding_6) / (np.linalg.norm(Sambit_embedding_5) * np.linalg.norm(Sambit_embedding_6))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Sambit_embedding_5 - Sambit_embedding_6)
print(f"Euclidean Distance: {euclidean_distance}")

In [ ]:
cosine_similarity = np.dot(Sambit_embedding_2, Sambit_embedding_3) / (np.linalg.norm(Sambit_embedding_2) * np.linalg.norm(Sambit_embedding_3))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Sambit_embedding_2 - Sambit_embedding_3)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.961376965045929
Euclidean Distance: 6.716508388519287


In [ ]:
cosine_similarity = np.dot(Sambit_embedding_1, Sambit_embedding_4) / (np.linalg.norm(Sambit_embedding_1) * np.linalg.norm(Sambit_embedding_4))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Sambit_embedding_1 - Sambit_embedding_4)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.8495546579360962
Euclidean Distance: 12.040750503540039


In [ ]:
cosine_similarity = np.dot(Sambit_embedding_3, Sambit_embedding_4) / (np.linalg.norm(Sambit_embedding_3) * np.linalg.norm(Sambit_embedding_4))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Sambit_embedding_3 - Sambit_embedding_4)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.7997197508811951
Euclidean Distance: 14.60883903503418


## Mix

In [ ]:
cosine_similarity = np.dot(embedding_1, embedding_5) / (np.linalg.norm(embedding_1) * np.linalg.norm(embedding_5))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_1 - embedding_5)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: -0.02307700179517269
Euclidean Distance: 33.08462905883789


In [ ]:
cosine_similarity = np.dot(embedding_4, embedding_3) / (np.linalg.norm(embedding_4) * np.linalg.norm(embedding_3))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_4 - embedding_3)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: -0.031456708908081055
Euclidean Distance: 32.406890869140625


In [ ]:
cosine_similarity = np.dot(embedding_6, embedding_2) / (np.linalg.norm(embedding_6) * np.linalg.norm(embedding_2))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_6 - embedding_2)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.05515352264046669
Euclidean Distance: 31.442956924438477


In [ ]:
cosine_similarity = np.dot(embedding_6, Dipu_embedding_1) / (np.linalg.norm(embedding_6) * np.linalg.norm(Dipu_embedding_1))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_6 - Dipu_embedding_1)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.08162474632263184
Euclidean Distance: 31.298892974853516


In [ ]:
cosine_similarity = np.dot(embedding_1, Dipu_embedding_1) / (np.linalg.norm(embedding_1) * np.linalg.norm(Dipu_embedding_1))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(embedding_1 - Dipu_embedding_1)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.1388643980026245
Euclidean Distance: 30.604055404663086


In [ ]:
cosine_similarity = np.dot(Dipu_embedding_1, Sambit_embedding_3) / (np.linalg.norm(Dipu_embedding_1) * np.linalg.norm(Sambit_embedding_3))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Dipu_embedding_1 - Sambit_embedding_3)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.07290656864643097
Euclidean Distance: 32.49578094482422


In [ ]:
cosine_similarity = np.dot(Dipu_embedding_2, Sambit_embedding_1) / (np.linalg.norm(Dipu_embedding_2) * np.linalg.norm(Sambit_embedding_1))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Dipu_embedding_2 - Sambit_embedding_1)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.003872606670483947
Euclidean Distance: 32.661712646484375


In [ ]:
cosine_similarity = np.dot(Sambit_embedding_4, Dipu_embedding_3) / (np.linalg.norm(Sambit_embedding_4) * np.linalg.norm(Dipu_embedding_3))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Sambit_embedding_4 - Dipu_embedding_3)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: -0.003889293409883976
Euclidean Distance: 32.384185791015625


In [ ]:
cosine_similarity = np.dot(Sambit_embedding_4, embedding_5) / (np.linalg.norm(Sambit_embedding_4) * np.linalg.norm(embedding_5))
print(f"Cosine Similarity: {cosine_similarity}")

euclidean_distance = np.linalg.norm(Sambit_embedding_4 - embedding_5)
print(f"Euclidean Distance: {euclidean_distance}")

Cosine Similarity: 0.02971397154033184
Euclidean Distance: 31.1262264251709


# Store Employee Data

### Creating employee file

In [ ]:
import pandas as pd

# Path to the employee database Excel file
employee_file = '/content/drive/MyDrive/AI Attendance System/System_2/employees.csv'

# Create initial employee database structure
columns = ['Employee_ID', 'Name', 'Embedding']
df = pd.DataFrame(columns=columns)
df.to_csv(employee_file, index=False)
print(f"Employee database created at {employee_file}")


Employee database created at /content/drive/MyDrive/AI Attendance System/System_2/employees.csv


## Add

In [ ]:
# img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Sambit_2.jpg"
# img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Kuldeep_1.jpeg"
# img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Jayanta_1.jpeg"
# img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Sir_1.jpg"
img_path = "/content/drive/MyDrive/AI Attendance System/TEST PICS/Chinmaya_1.jpeg"
embedding = find_embedding(img_path)

/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


In [ ]:
import pandas as pd
import pickle
import base64
import numpy as np

employee_file = '/content/drive/MyDrive/AI Attendance System/System_2/employees.csv'

# Add a new employee to the database
def add_employee_to_csv(employee_id, name, embedding):
    try:
        df = pd.read_csv(employee_file)
    except FileNotFoundError:
        df = pd.DataFrame(columns=["Employee_ID", "Name", "Embedding"])

    # Serialize and encode the embedding
    embedding_serialized = base64.b64encode(pickle.dumps(embedding)).decode('utf-8')

    # Append the new employee data
    new_data = pd.DataFrame([{
        "Employee_ID": employee_id,
        "Name": name,
        "Embedding": embedding_serialized
    }])
    df = pd.concat([df, new_data], ignore_index=True)

    # Save back to CSV
    df.to_csv(employee_file, index=False)
    print(f"Employee {name} added successfully.")

e_id = input()
Name = input()
add_employee_to_csv(e_id, Name, embedding)

CDSR_INT_000003
Chinmaya Jyotishi
Employee Chinmaya Jyotishi added successfully.


## Delete

In [ ]:
def delete_employee_from_csv(employee_id):
    # Load the existing database
    df = pd.read_csv(employee_file)

    # Filter out the employee
    df = df[df['Employee_ID'] != employee_id]

    # Save back to Excel
    df.to_csv(employee_file, index=False)
    print(f"Employee with ID {employee_id} deleted successfully.")

delete_e_id = input()
delete_employee_from_csv(delete_e_id)


CDSR_INT_000052
Employee with ID CDSR_INT_000052 deleted successfully.


# Recognize and Record Attendance

In [ ]:
# def recognize_person_from_csv(face_embedding, threshold=0.5):
#     try:
#         # Load the database
#         df = pd.read_csv(employee_file)
#     except FileNotFoundError:
#         print("Employee database not found.")
#         return None, None

#     for _, row in df.iterrows():
#         # Decode and deserialize the embedding
#         stored_embedding = pickle.loads(base64.b64decode(row['Embedding']))
#         # Calculate distance between embeddings
#         distance = np.linalg.norm(face_embedding - stored_embedding)
#         if distance < threshold:
#             return row['Name'], row['Employee_ID']
#     return None, None

In [8]:
import pandas as pd
import numpy as np
import pickle
import base64
from sklearn.metrics.pairwise import cosine_similarity

def recognize_person_from_csv(face_embedding, cosine_threshold=0.7, euclidean_threshold=20):
    try:
        # Load the employee database
        df = pd.read_csv(employee_file)
    except FileNotFoundError:
        print("Employee database not found.")
        return None, None

    for _, row in df.iterrows():
        # Decode and deserialize the stored embedding from the CSV
        stored_embedding = pickle.loads(base64.b64decode(row['Embedding']))

        # Calculate Euclidean distance
        euclidean_distance = np.linalg.norm(face_embedding - stored_embedding)

        # Calculate cosine similarity
        cosine_sim = cosine_similarity([face_embedding], [stored_embedding])[0][0]

        # Check if either of the conditions is satisfied
        if cosine_sim > cosine_threshold or euclidean_distance < euclidean_threshold:
            return row['Name'], row['Employee_ID']

    return None, None


In [9]:
from datetime import datetime

# Path to attendance log Excel file
attendance_file = '/content/drive/MyDrive/AI Attendance System/System_2/attendance_log.xlsx'

# Create an initial attendance log structure (if file doesn't exist)
try:
    pd.read_excel(attendance_file)
except FileNotFoundError:
    columns = ['Employee_ID', 'Name', 'Timestamp']
    pd.DataFrame(columns=columns).to_excel(attendance_file, index=False)

# Record attendance in the Excel file
def record_attendance_in_excel(employee_id, name):
    # Load the existing attendance log
    df = pd.read_excel(attendance_file)

    # Add a new record
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    new_data = {'Employee_ID': employee_id, 'Name': name, 'Timestamp': timestamp}
    df = pd.concat([df, pd.DataFrame([new_data])], ignore_index=True)

    # Save back to Excel
    df.to_excel(attendance_file, index=False)
    print(f"Attendance recorded for {name} at {timestamp}.")


# Camera

In [ ]:
def process_camera_frame():
    # Capture live frame
    cap = cv2.VideoCapture(0)
    ret, frame = cap.read()
    cap.release()

    if ret:
        # Extract face and generate embedding
        face = extract_face(frame)
        if face is not None:
            embedding = get_embedding(face)

            # Recognize person and record attendance
            name, employee_id = recognize_person_from_csv(embedding)
            if name:
                record_attendance_in_excel(employee_id, name)
            else:
                print("Person not recognized.")
        else:
            print("No face detected.")
    else:
        print("Failed to capture image.")


# Attendance Logs

In [ ]:
def export_attendance_log():
    df = pd.read_excel(attendance_file)
    output_csv = '/content/drive/MyDrive/AI Attendance System/System_2/attendance_log.csv'

    df.to_csv(output_csv, index=False)
    print(f"Attendance log exported to {output_csv}")


In [ ]:
process_camera_frame()

Failed to capture image.


# Test

In [ ]:

test_image_path = '/content/drive/MyDrive/AI Attendance System/TEST PICS/Chinmaya_2.jpeg'
# face = extract_face(test_image_path)

if test_image_path is not None:
    test_embedding = find_embedding(test_image_path)
    print("Embedding generated successfully!")

    # Compare test embedding with stored embeddings and recognize the person
    name, employee_id = recognize_person_from_csv(test_embedding)

    if name:
        print(f"Recognized: {name}, Employee ID: {employee_id}")

        # Record attendance
        record_attendance_in_excel(employee_id, name)
        print("Attendance recorded successfully!")
    else:
        print("No match found in the dataset.")
else:
    print("No face detected in the image.")


/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


Embedding generated successfully!
Recognized: Chinmaya Jyotishi, Employee ID: CDSR_INT_000003
Attendance recorded for Chinmaya Jyotishi at 2024-11-28 12:16:51.
Attendance recorded successfully!


In [ ]:
import pickle
import base64
import numpy as np
import pandas as pd

# Path to the test image
test_image_path = '/content/drive/MyDrive/AI Attendance System/TEST PICS/Kuldeep 2.jpeg'

if test_image_path is not None:

    test_embedding = get_embedding(face)
    print("Embedding generated successfully!")

    # Step 3: Recognize the person by comparing embeddings
    def recognize_person_from_csv(face_embedding, threshold=0.6):
        """
        Compare the test embedding with stored embeddings in the CSV file and recognize the person.

        Parameters:
            face_embedding (np.array): The embedding of the face to recognize.
            threshold (float): Threshold for considering a match (default is 0.6).

        Returns:
            tuple: Name and employee ID if a match is found, otherwise (None, None).
        """
        df = pd.read_csv(employee_file)
        for _, row in df.iterrows():
            # Deserialize the stored embedding
            stored_embedding = pickle.loads(base64.b64decode(row['Embedding']))

            # Calculate Euclidean distance
            distance = np.linalg.norm(face_embedding - stored_embedding)
            if distance < threshold:
                return row['Name'], row['Employee ID']
        return None, None

    # Recognize the person
    name, employee_id = recognize_person_from_csv(test_embedding)
    if name:
        print(f"Recognized: {name}, Employee ID: {employee_id}")

        # Step 4: Record attendance
        record_attendance_in_excel(employee_id, name)
        print("Attendance recorded successfully!")
    else:
        print("No match found in the dataset.")
else:
    print("No face detected in the image.")


Face extracted successfully!
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
Embedding generated successfully!
No match found in the dataset.


In [10]:
!pip freeze > requirements.txt


In [13]:
import tensorflow as tf
import numpy as np
import insightface

print("TensorFlow version:", tf.__version__)
print("NumPy version:", np.__version__)
print("InsightFace version:", insightface.__version__)


TensorFlow version: 2.17.1
NumPy version: 1.26.4
InsightFace version: 0.7.3


In [12]:
import sys
print("Python version:", sys.version)


Python version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
